version: "3.9"

services:
  writer:
    build:
      context: .
      dockerfile: writer/Dockerfile
    restart: always
    container_name: writer-app
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./logs
        target: /app/writer/logs

  handler:
    build:
      context: .
      dockerfile: handler/Dockerfile
    restart: always
    container_name: handler-app
    env_file:
      - .env

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: always
    container_name: gateway-app
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  logs:
